fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: uncrustify
      - id: cppcheck
      - id: include-what-you-use